AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway with usage plan, API key and WAF
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: NextVideoApi
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod
    DependsOn: RestApi
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: ServerUsagePlan
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: prod
      Throttle:
        BurstLimit: 500
        RateLimit: 1000
  ServerApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: ServerToServerKey
      Enabled: true
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ServerApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: ApiGatewayWebACL
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: apiGatewayWebAcl
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: awsCommonRules
            SampledRequestsEnabled: true
        - Name: RateLimit
          Priority: 2
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: rateLimit
            SampledRequestsEnabled: true
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      WebACLArn: !GetAtt WebACL.Arn
      ResourceArn: !Sub arn:aws:apigateway:${AWS::Region}::/restapis/${RestApi}/stages/prod
Outputs:
  ApiKeyId:
    Value: !Ref ServerApiKey
