service: next-video-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

functions:
  getVideo:
    handler: dist/videos.getVideo
    events:
      - http:
          path: videos/{id}
          method: get
  getPlaylist:
    handler: dist/playlists.getPlaylist
    events:
      - http:
          path: playlists/{id}
          method: get
  search:
    handler: dist/search.search
    events:
      - http:
          path: search
          method: get
