AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to scan uploaded media with ClamAV and quarantine suspicious files.

Parameters:
  QuarantineBucketName:
    Type: String
    Default: STLS-quarantine

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket

  QuarantineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref QuarantineBucketName

  AlertTopic:
    Type: AWS::SNS::Topic

  ScanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: s3_object
          AttributeType: S
      KeySchema:
        - AttributeName: s3_object
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scan_lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 900
      MemorySize: 1024
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          QUARANTINE_BUCKET: !Ref QuarantineBucketName
          SNS_TOPIC_ARN: !Ref AlertTopic
          DDB_TABLE: !Ref ScanTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
        - S3WritePolicy:
            BucketName: !Ref QuarantineBucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref ScanTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AlertTopic.TopicName

Outputs:
  UploadBucketName:
    Value: !Ref UploadBucket
  QuarantineBucketName:
    Value: !Ref QuarantineBucket
  AlertTopicArn:
    Value: !Ref AlertTopic
  ScanTableName:
    Value: !Ref ScanTable
