AWSTemplateFormatVersion: '2010-09-09'
Description: CodeDeploy blue-green deployment with canary traffic shifting and automatic rollback.

Parameters:
  ClusterName:
    Type: String
  ServiceName:
    Type: String
  ProdListenerArn:
    Type: String
  TestListenerArn:
    Type: String
  TargetGroupBlueName:
    Type: String
  TargetGroupGreenName:
    Type: String
  LoadBalancerFullName:
    Type: String
  TargetGroupFullName:
    Type: String

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: ECS

  CanaryDeploymentConfig:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      ComputePlatform: ECS
      TrafficRoutingConfig:
        Type: TimeBasedCanary
        TimeBasedCanary:
          CanaryPercentage: 25
          CanaryInterval: 5

  Http5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ServiceName}-5xx'
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerFullName
        - Name: TargetGroup
          Value: !Ref TargetGroupFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

  UnhealthyHostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ServiceName}-unhealthy'
      Namespace: AWS/ApplicationELB
      MetricName: UnHealthyHostCount
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerFullName
        - Name: TargetGroup
          Value: !Ref TargetGroupFullName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: !Ref CanaryDeploymentConfig
      ServiceRoleArn: REPLACE_WITH_CODEDEPLOY_ROLE_ARN # TODO: update with actual IAM role ARN
      DeploymentStyle:
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - !Ref ProdListenerArn
            TestTrafficRoute:
              ListenerArns:
                - !Ref TestListenerArn
            TargetGroups:
              - Name: !Ref TargetGroupBlueName
              - Name: !Ref TargetGroupGreenName
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_ALARM
      AlarmConfiguration:
        Enabled: true
        Alarms:
          - Name: !Ref Http5xxAlarm
          - Name: !Ref UnhealthyHostAlarm

Outputs:
  ApplicationName:
    Value: !Ref CodeDeployApplication
  DeploymentGroupName:
    Value: !Ref CodeDeployDeploymentGroup
  DeploymentConfigName:
    Value: !Ref CanaryDeploymentConfig
