AWSTemplateFormatVersion: '2010-09-09'
Description: Alarms and SNS topic for next-video-site SLO breaches
Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for alarm notifications
Resources:
  SLOAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail
  StartupTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Startup time p95 above 3s'
      Namespace: 'NextVideoSite'
      MetricName: 'StartupTime'
      ExtendedStatistic: 'p95'
      Period: 60
      EvaluationPeriods: 1
      Threshold: 3000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SLOAlarmTopic
  ApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'API latency p95 above 500ms'
      Namespace: 'NextVideoSite'
      MetricName: 'ApiLatency'
      ExtendedStatistic: 'p95'
      Period: 60
      EvaluationPeriods: 1
      Threshold: 500
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SLOAlarmTopic
  PlayerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Player errors detected'
      Namespace: 'NextVideoSite'
      MetricName: 'PlayerErrors'
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SLOAlarmTopic
  RebufferDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Rebuffer duration avg above 500ms'
      Namespace: 'NextVideoSite'
      MetricName: 'RebufferDuration'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 500
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SLOAlarmTopic
Outputs:
  AlarmTopicArn:
    Description: ARN of SNS topic for SLO alarms
    Value: !Ref SLOAlarmTopic
