AWSTemplateFormatVersion: '2010-09-09'
Description: WAF configuration for Next Video Site with AWS managed rule groups and GraphQL introspection blocking.

Resources:
  GraphQLIntrospectionPattern:
    Type: AWS::WAFv2::RegexPatternSet
    Properties:
      Name: GraphQLIntrospectionPattern
      Scope: CLOUDFRONT
      RegularExpressionList:
        - "__schema"
        - "__type"

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: NextVideoSiteWebACL
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: NextVideoSiteWebACL
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedCommonRules
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedBadInputsRules
            SampledRequestsEnabled: true
        - Name: BlockGraphQLIntrospection
          Priority: 10
          Action:
            Block: {}
          Statement:
            RegexPatternSetReferenceStatement:
              Arn: !GetAtt GraphQLIntrospectionPattern.Arn
              FieldToMatch:
                Body: {}
              TextTransformations:
                - Priority: 0
                  Type: LOWERCASE
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: BlockGraphQLIntrospection
            SampledRequestsEnabled: true

  GraphQLIntrospectionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: GraphQLIntrospectionBlocks
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 0
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/WAFV2
              MetricName: BlockedRequests
              Dimensions:
                - Name: WebACL
                  Value: !Ref WebACL
                - Name: Region
                  Value: Global
                - Name: Rule
                  Value: BlockGraphQLIntrospection
            Period: 300
            Stat: Sum
          ReturnData: true
      TreatMissingData: notBreaching
      AlarmDescription: Alarm when GraphQL introspection requests are blocked.
